# Site settings
title: eruditely
tag_text: eruditely
description: Simple.
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
